name: gps_tracker
description: A simple personal GPS activity tracker (bike, hike, ski touring).
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  geolocator: ^13.0.1
  flutter_foreground_task: ^8.17.0
  permission_handler: ^11.3.1
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  sqflite: ^2.3.3
  path: ^1.9.0
  path_provider: ^2.1.4
  gpx: ^2.3.0
  share_plus: ^10.0.2
  intl: ^0.19.0

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
